### ISSUE TITLE
[FEATURE]: Additional environment variables for traefik bouncer

### ISSUE THREAD

**Issue by lexermal** [crowdsecurity/helm-charts#106]
Hello, 

I want to customize the response message of the Traefik bouncer. The bouncer allows setting it via CROWDSEC_BOUNCER_BAN_RESPONSE_CODE and CROWDSEC_BOUNCER_BAN_RESPONSE_MSG but the Helm chart does not let set them.

This feature would be handy for showing a more user-friendly message to the user that gets blocked.

**Comment by he2ss** [comment]
Hi @lexermal,

Done in https://github.com/crowdsecurity/helm-charts/pull/138
