### ISSUE TITLE
Auto update helm chart

### ISSUE THREAD

**Issue by RelativeSure** [crowdsecurity/helm-charts#115]
I really wish that the helm charts can be somehow more automatically updated whenever there's a new CrowdSec release.
It takes days if not weeks for a new helm chart release.

**Comment by he2ss** [comment]
Hi @RelativeSure,

Sorry for the delay.
We were little busy on others important tasks. We take now more time for the helm-charts repo.

We'll update the chart soon on 1.6.1 crowdsec version to include some new features (especially the high availability to be able to add more replicas on k8s).

**Comment by he2ss** [comment]
Hi @RelativeSure,

A new release is available.
