### ISSUE TITLE
crowdsec-lapi frequently in CrashBackLoopOff with traefik-bouncer-plugin

### ISSUE THREAD

**Issue by pfaelzerchen** [crowdsecurity/helm-charts#128]
I have a crowdsec deployment running for some days doing analysis only. Then I activated the traefik-bouncer-plugin as given in <https://www.crowdsec.net/blog/integrating-crowdsec-kubernetes-tls>. And added it as default middleware.

Almost immediately, any request to traefik was blocked. cscli decisions list didn't show the IP as banned. But I recognized that the shell on the pod terminated within short time frames. The log files showed, that it frequently crashed and come up.

I then switched to stream mode in the bouncer-plugin to reduce requests to the lapi-server. That didn't have any effect.

Taking the bouncer from the default chain (basically from any chain) resolved the issue. The lapi-server runs stable again.

Then I switched the TLS auth to the LapiKey-method (cscli bouncers add traefik) and brought the bouncer back. It had the same effect. lapi-server frequently crashed. So there seems to be something wrong with this service.

**Comment by pfaelzerchen** [comment]
OK, while writing this issue, someone pointed out to me that it could be triggered by resource limits. And indeed, there was an oomkilled event. With

```yaml
lapi:
  resources:
    limits:
      memory: 250Mi
    requests:
      cpu: 150m
      memory: 250Mi
```

it works stable. Probably, it is a good idea to set higher defaults in the chart's value.yaml.

**Comment by mathias-ws** [comment]
I also had the same issue with the lua-bouncer-plugin, the suggested fix seemed to work.
