### ISSUE TITLE
Ability to connect to multiple LAPI from agent

### ISSUE THREAD

**Issue by R-Nabil** [crowdsecurity/helm-charts#144]
Would it be possible to add the ability to connect to multiple LAPI from the agent ?

The use case is my k3s crowdsec is used for both external and internal facing services. The internal one doesn't need to have a remote LAPI (local is faster) while the external go through a VPS gateway that implements the firewall bouncer.

**Comment by LaurenceJJones** [comment]
Closing issue as not possible, the user has an answer via [discord](https://discord.gg/crowdsec)

but TLDR is CrowdSec security engine can only have a single LAPI as the parent, if the user wishes to have a more replication setup then they would have to do something custom as it not support via us.
