### ISSUE TITLE
[Feature] Add probes for agent daemonSet

### ISSUE THREAD

**Issue by sipr-invivo** [crowdsecurity/helm-charts#158]
Hello there 👋 

I was wondering whether it would be possible to add probes (liveness, readiness and startup) for agent too, and not only for lapi.

It seems that there are no healthcheck endpoints available on the agent, but we could add TCP probes.

WDYT?

**Comment by he2ss** [comment]
Hi @sipr-invivo,

It seems a good Idea. the agent exposed a metrics endpoint. We can use it for both liveness, readiness.
