### ISSUE TITLE
[Feature proposal] Add the posibility via Cronjob to execute cscli machines prune with parameters for the LAPI

### ISSUE THREAD

**Issue by cstisa** [crowdsecurity/helm-charts#175]
Dear all,

Thanks for this helm chart !

It will be great to have the possibility to have a kind of cronjob that execute prune action on machines for LAPI, in order to purge nodes that are not reporting since a while to the LAPI (https://docs.crowdsec.net/docs/cscli/cscli_machines_prune) 

Thanks again 

Have a nice day.

Best Regards,

**Comment by LaurenceJJones** [comment]
> Dear all,
> 
> Thanks for this helm chart !
> 
> It will be great to have the possibility to have a kind of cronjob that execute prune action on machines for LAPI, in order to purge nodes that are not reporting since a while to the LAPI (https://docs.crowdsec.net/docs/cscli/cscli_machines_prune)
> 
> Thanks again
> 
> Have a nice day.
> 
> Best Regards,

You can configure a flush option within the configuration:

https://docs.crowdsec.net/docs/next/configuration/crowdsec_configuration#flush

Which does the exact same thing as prune

**Comment by cstisa** [comment]
Hi @LaurenceJJones ,

Thanks for the help, we have set this , thank you.

Closing the case.

Best Regards,
