### ISSUE TITLE
Crowdsec agent fails to start waiting for lapi

### ISSUE THREAD

**Issue by rlex** [crowdsecurity/helm-charts#3]
Subj.
Deployed as described here: https://crowdsec.net/blog/kubernetes-crowdsec-integration/

Agent sitting in "waiting" state, waiting for "wait-for-lapi" container to end, despite lapi container started.

(btw, blog really messed up with yaml indentation)

**Comment by rlex** [comment]
Oh, it seems like i found the issue.
```
nc: bad address 'crowdsec-service.crowdsec'
```
It seems like "crowdsec" namespace is hardcoded?

**Comment by mmetc** [comment]
Hi, thanks for the report!

Indeed, the namespace was hardcoded, and it can be left out of the URL - `http://crowdsec-service:8080`
