### ISSUE TITLE
Add persistent volume for LAPI dashboard (Metabase)

### ISSUE THREAD

**Issue by keliansb** [crowdsecurity/helm-charts#55]
# Environment
Helm chart : crowdsec
Helm chart version : 0.5.0

# Issue
Currently if the pod for the Local API is restarted the configurations made in the dashboard are lost (changing user password or language preferences for example).

# Proposed solution
We could add an option to the Helm chart in `lapi.persistentVolume` to create a PVC for the metabase data, similar to the crowdsec-db and crowdsec-config PVCs.

**Comment by bmalynovytch** [comment]
Seems to be related to #11
Right now, dashboard modifications are stored in `/metabase-data` whish is declared as an `emptyDir`, while the persistent volume is attached to `/var/lib/crowdsec/data` which seems to only contain data that are reset at restart.

I guess there was an inversion between mount points.

**Comment by bmalynovytch** [comment]
Ping @he2ss 
This issue should be treated as critical.
Any instance of Crowdsec running with this Helm charts leaves the dashboard running with the default password (and loosing real user data) at each pod restart.

I'll try to find some time to make a PR, but fixing shouldn't take more than a couple of minutes.

Credentials are stored in the volume defined here: https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/templates/lapi-deployment.yaml#L258
It'd better be a dedicated PVC (probably overkill) or as a subdir of Crowdsec's data PV (here https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/templates/lapi-deployment.yaml#L262)

**Comment by albundy83** [comment]
Hello,
any update on this one ?

**Comment by bmalynovytch** [comment]
@albundy83 did a PR yesterday, waiting for review and merge.
