### ISSUE TITLE
Add ingress for lapi traffic

### ISSUE THREAD

**Issue by charims** [crowdsecurity/helm-charts#57]
When setting up a multi-agent and bouncer environment, sometimes we have external devices which communicate with the lapi api. Exposing an ingress for this traffic which is eventually bound for 8080 would really help facilitate a centralized api agent architecture running in k8s while running external agents and/or bouncers, for example an opnsense system. From what I can tell, the only ingress in this chart is for the metabase dashboard.

**Comment by he2ss** [comment]
Your PR was merged. Thanks for the contribution :+1:
