### ISSUE TITLE
Outdated crowdsec version

### ISSUE THREAD

**Issue by glenndehaan** [crowdsecurity/helm-charts#62]
As the title suggests, it seems like the current chart 0.6.0 is using an outdated version of crowdsec causing these warnings:

```
time="11-10-2022 05:01:44 PM" level=warning msg="Crowdsec is not the latest version. Current version is 'v1.3.4' and the latest stable version is 'v1.4.1'. Please update it!"
```

Is is possible that we could get a bump for this?

**Comment by he2ss** [comment]
fixed here https://github.com/crowdsecurity/helm-charts/pull/61
