### ISSUE TITLE
Add health timeout

### ISSUE THREAD

**Issue by Vertiwell** [crowdsecurity/helm-charts#63]
Hi,
Is it possible to pull this value to the chart?
HEALTH_CHECKER_TIMEOUT_DURATION

Thank you.

**Comment by he2ss** [comment]
Hi @Vertiwell,

You mean adding the ability to set the Probes (readiness, liveness & startup) timeouts ? 
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes

**Comment by he2ss** [comment]
I think I finally figured out what you want exactly. It's about being able to modify the traefik bouncer env variables so you can add this `HEALTH_CHECKER_TIMEOUT_DURATION` variable.
