### ISSUE TITLE
Crowdsec agent cannot parse Nginx ingress logs unless "container_runtime: nginx"

### ISSUE THREAD

**Issue by william-elastisys** [crowdsecurity/helm-charts#66]
I installed crowdsec on kubernetes similarly to https://github.com/crowdsecurity/helm-charts/issues/46 and i got a similar results, all logs where unparsed by the `nginx-logs` parser.

I got it working by setting `container_runtime: nginx` in the values file for the crowdsec helm-chart. Is this the exptected behaviour or have i missconfigured something else? I couldn't find this in the documentation

**Comment by he2ss** [comment]
Hi @william-elastisys,

This option can be set on ly to `docker` or `cri`. It's about the log format your containers engine produce.
In normal clusters it will mainly be json format, so `docker`. But sometimes with kind or k3s, the containers output logs are in CRI format, that why we use `cri`.

So I don't know if it really worked on your side, you need to fix the value for this parameter.

**Comment by william-elastisys** [comment]
Hi, I get the following results with different values of `container_runtime`

With `container_runtime: nginx`
![Pasted image 20230111081128](https://user-images.githubusercontent.com/112404889/211745406-ad70fc24-9ae9-4f2f-be34-3f19b85dbaa3.png)

With `container_runtime: cri`
![Pasted image 20230111081304](https://user-images.githubusercontent.com/112404889/211745625-4d34413d-b6a8-46af-ab08-c7a1da204357.png)

With `container_runtime: docker`
![Pasted image 20230111082628](https://user-images.githubusercontent.com/112404889/211745711-66ed2854-095a-41ad-844f-6cd7a1f0dd1b.png)

With `container_runtime: containerd`
![Pasted image 20230111083011](https://user-images.githubusercontent.com/112404889/211745775-b68fdac3-1f00-4499-be5b-741b8276d3d7.png)

**Comment by DinStamou** [comment]
The same issue here. I confirm it works with the workaround from @william-elastisys.

**Comment by brightdroid** [comment]
I've the same problem with traefik.

As the docs for [acquisition](https://docs.crowdsec.net/docs/concepts/#acquisition) and [file datasource](https://docs.crowdsec.net/docs/data_sources/file) describe:

> The labels part is here to tag the incoming logs with a type. labels.type are used by the parsers to know which logs to process.

  So the [acquis-configmap.yaml](https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/templates/acquis-configmap.yaml#L18) is probably wrong and should look like this:
```yaml
# ...
    labels:
      type: {{ .program }}
```
Though I'd rename the param to type, like this:
```yaml
# ...
    labels:
      type: {{ .type }}
```
So you have to write this in your helm values.yaml:
```yaml
agent:
  acquisition:
    - namespace: traefik
      podName: traefik-*
      type: traefik
```

**Comment by brightdroid** [comment]
Fixed for my test-setup (with local IPs) by adding this to values.yaml:
```yaml
container_runtime: containerd
agent:
  env:
    - name: PARSERS
      value: "crowdsecurity/cri-logs"
    - name: DISABLE_PARSERS
      value: "crowdsecurity/whitelists"
```

**Comment by LaurenceJJones** [comment]
> I've the same problem with traefik.
> 
> As the docs for [acquisition](https://docs.crowdsec.net/docs/concepts/#acquisition) and [file datasource](https://docs.crowdsec.net/docs/data_sources/file) describe:
> 
> > The labels part is here to tag the incoming logs with a type. labels.type are used by the parsers to know which logs to process.
> 
> So the [acquis-configmap.yaml](https://github.com/crowdsecurity/helm-charts/blob/main/charts/crowdsec/templates/acquis-configmap.yaml#L18) is probably wrong and should look like this:
> 
> ```yaml
> # ...
>     labels:
>       type: {{ .program }}
> ```
> 
> Though I'd rename the param to type, like this:
> 
> ```yaml
> # ...
>     labels:
>       type: {{ .type }}
> ```
> 
> So you have to write this in your helm values.yaml:
> 
> ```yaml
> agent:
>   acquisition:
>     - namespace: traefik
>       podName: traefik-*
>       type: traefik
> ```

This is not advised as you need to have a s00 parser which is normally `syslog`, `docker` or `cri`. Which prepares the log for the next stage which the application parser will then correct parse just the message.

**Comment by LaurenceJJones** [comment]
> Hi, I get the following results with different values of `container_runtime`
> 
> With `container_runtime: nginx` ![Pasted image 20230111081128](https://user-images.githubusercontent.com/112404889/211745406-ad70fc24-9ae9-4f2f-be34-3f19b85dbaa3.png)
> 
> With `container_runtime: cri` ![Pasted image 20230111081304](https://user-images.githubusercontent.com/112404889/211745625-4d34413d-b6a8-46af-ab08-c7a1da204357.png)
> 
> With `container_runtime: docker` ![Pasted image 20230111082628](https://user-images.githubusercontent.com/112404889/211745711-66ed2854-095a-41ad-844f-6cd7a1f0dd1b.png)
> 
> With `container_runtime: containerd` ![Pasted image 20230111083011](https://user-images.githubusercontent.com/112404889/211745775-b68fdac3-1f00-4499-be5b-741b8276d3d7.png)

Setting the container runtime to nginx would work technically as the log is embedded within the log line, however, for multiple container types SQL / nginx this will not work in the long run.

From my experience you most likely needed to set the runtime to `cri` but you didnt add the `cri` collection to your values.yaml so it wasnt installed for crowdsec to use.

**Comment by LaurenceJJones** [comment]
> The same issue here. I confirm it works with the workaround from @william-elastisys.

This is not advised please see my reply above

**Comment by joaogbcravo** [comment]
I'm having the same problem.

I followed your advice @LaurenceJJones. Activated the cri parser, and set it as the type

```
crowdsec-agent-f4b9x:/# cscli parsers list

PARSERS
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
 Name                             📦 Status   Version   Local Path
───────────────────────────────────────────────────────────────────────────────────────────────────────────────
 crowdsecurity/cri-logs           ✔️ enabled   0.1       /etc/crowdsec/parsers/s00-raw/cri-logs.yaml
 crowdsecurity/dateparse-enrich   ✔️ enabled   0.2       /etc/crowdsec/parsers/s02-enrich/dateparse-enrich.yaml
 crowdsecurity/docker-logs        ✔️ enabled   0.1       /etc/crowdsec/parsers/s00-raw/docker-logs.yaml
 crowdsecurity/geoip-enrich       ✔️ enabled   0.2       /etc/crowdsec/parsers/s02-enrich/geoip-enrich.yaml
 crowdsecurity/http-logs          ✔️ enabled   1.1       /etc/crowdsec/parsers/s02-enrich/http-logs.yaml
 crowdsecurity/nginx-logs         ✔️ enabled   1.3       /etc/crowdsec/parsers/s01-parse/nginx-logs.yaml
 crowdsecurity/sshd-logs          ✔️ enabled   2.0       /etc/crowdsec/parsers/s01-parse/sshd-logs.yaml
 crowdsecurity/syslog-logs        ✔️ enabled   0.8       /etc/crowdsec/parsers/s00-raw/syslog-logs.yaml
 crowdsecurity/whitelists         ✔️ enabled   0.2       /etc/crowdsec/parsers/s02-enrich/whitelists.yaml

```

Content of /etc/crowdsec/acquis.yaml

```
---
filenames:
  - /var/log/containers/*-nginx-ingress-*_*_*.log
force_inotify: true
labels:
  type: cri
  program: nginx
```

Cscli explain with type "nginx" 
```
line: 2023-01-26T12:56:15.04394063Z stdout F 164.128.158.100 - - [26/Jan/2023:12:56:15 +0000] "GET /api/live/ws HTTP/1.1" 401 27 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36" "-"
        ├ s00-raw
        |       ├ 🔴 crowdsecurity/cri-logs
        |       ├ 🔴 crowdsecurity/docker-logs
        |       ├ 🟢 crowdsecurity/non-syslog (first_parser)
        |       └ 🔴 crowdsecurity/syslog-logs
        ├ s01-parse
        |       └ 🟢 crowdsecurity/nginx-logs (+23 ~2)
        ├ s02-enrich
        |       ├ 🟢 crowdsecurity/dateparse-enrich (+2 ~1)
        |       ├ 🟢 crowdsecurity/geoip-enrich (+13)
        |       ├ 🟢 crowdsecurity/http-logs (+7)
        |       └ 🟢 crowdsecurity/whitelists (unchanged)
        ├-------- parser success 🟢
        ├ Scenarios
                └ 🟢 crowdsecurity/http-crawl-non_statics

```

As you can see cri-logs fail. What can it be?

**Comment by joaogbcravo** [comment]
Nevermind. It's working. 

First was the type not well defined (it was docker instead of containerd) 
Then, it was a stupid miss config on my side, while playing around.

**Comment by marijusGood** [comment]
Hi team,

I seem to have the same problem as described before where none of my logs get parsed. I am deploying everything within a k8s cluster. The output of my **cscli metrics**

```
╭──────────────────────────────────────────────────────────────┬────────────┬──────────────┬────────────────┬────────────────────────┬───────────────────╮
│                            Source                            │ Lines read │ Lines parsed │ Lines unparsed │ Lines poured to bucket │ Lines whitelisted │
├──────────────────────────────────────────────────────────────┼────────────┼──────────────┼────────────────┼────────────────────────┼───────────────────┤
│ file:/var/log/containers/nginx-ingress-microk8s-controller-l │ 1          │ -            │ 1              │ -                      │ -                 │
│ dlp5_ingress_nginx-ingress-microk8s-ace27de928e788d77337c3c2 │            │              │                │                        │                   │
│ a8a60698f9b3a42109a834fb0d88a891eb3f04aa.log                 │            │              │                │                        │                   │
╰──────────────────────────────────────────────────────────────┴────────────┴──────────────┴────────────────┴────────────────────────┴───────────────────╯

Parser Metrics:
╭────────────────────────────────┬──────┬────────┬──────────╮
│             Parsers            │ Hits │ Parsed │ Unparsed │
├────────────────────────────────┼──────┼────────┼──────────┤
│ child-crowdsecurity/nginx-logs │ 3.00k    │ -      │ 3.00k        │
│ crowdsecurity/nginx-logs       │ 3.00k    │ -      │ 3.00k        │
│ crowdsecurity/non-syslog       │ 3.00k    │ 3.00k      │ -        │
╰────────────────────────────────┴──────┴────────┴──────────╯
```
when my nginx logs look like this:
```
83.150.2.35 - - [28/Jun/2024:14:15:08 +0000] "GET /selfTestPci586.d HTTP/2.0" 200 53 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 32 0.204 [es-dev-es-dev-443] [] 10.1.187.164:8443 53 0.203 200 d77633989c1e405f9321cfa84f545197
83.150.2.35 - - [28/Jun/2024:14:15:08 +0000] "GET /selfTestPci586.d HTTP/2.0" 200 53 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" 32 0.183 [es-dev-es-dev-443] [] 10.1.187.164:8443 53 0.182 200 733fed93485463aa28918026e93ced5b
```

and my values.yaml is:
```
agent:
  acquisition:
    - namespace: ingress
      # The pod name
      podName: nginx-ingress-microk8s-controller-*
      program: nginx

  # Those are ENV variables
  env:
  - name: DISABLE_ONLINE_API
    value: "true"
  - name: COLLECTIONS
    value: "crowdsecurity/nginx"
lapi:
  env:
    - name: DISABLE_ONLINE_API
      value: "true"
```

I tried setting container_runtime to cri, docker, container and ngnix with no avail. I also tried to add:
```
- name: PARSERS
    value: "crowdsecurity/cri-logs"
```

but it did not help
