### ISSUE TITLE
Fails to run - Crowdsec 1.4.3

### ISSUE THREAD

**Issue by neilmfrench** [crowdsecurity/helm-charts#67]
I am running Crowdsec on Kubernetes (v1.24.8), using the Crowdsec Helm chart (0.7.0). 

My cluster consists of 4 nodes. Per the Helm installation, a daemonset is created with an agent pod on each node and a single LAPI pod. 

I am defining secrets.username and secrets.password in the Helm values file. 

I updated the Crowdsec image to 1.4.3 and found that if the crowdsec LAPI pod restarts for any reason, it will fail to start with an error: 

`unable to create machine: user '<user from secrets.username>': user already exist"`

In Crowdsec 1.42, the error is still in the logs (and says its fatal), but it still starts up properly.

What's the correct configuration for a multi-node deployment? It seems like each agent should have its own username/password, but as far as I can tell the chart doesn't support this.

**Comment by maciejaszek** [comment]
The same issue occurs with 0.8.0.

**Comment by SNThrailkill** [comment]
I am also seeing this error. Cant figure a way around it.

**Comment by mmetc** [comment]
We should release 1.4.4-rc1 tomorrow which fixes the crash.

However, the agents in each node are still seen as a single (roaming) agent which changes IP quite often. It should work the same, but you can't see all the machines from the LAPI.

We should look for mechanisms to have per-node passwords without having to run something by hand each time a node is added, or a full fledged operator (both solutions are quite extreme).

Starting from v0.8 of the chart, you can enable TLS and you don't need to register agents or bouncers anymore. The LAPI correctly sees the agents as separate machines. The limitation in this case is the current version does not support HTTP and HTTPS at the same time, so all of your bouncers need to support TLS. We should release a short tutorial, soon.

**Comment by he2ss** [comment]
Hi,

With the release 0.8.3 it's now fixed. By default, we consider that the agents should not have persistency (as the agent config can be in the values.yaml). If the user wants persistence, he must configure his cluster to support ReadWriteMany in PV and enable it in the chart values.
