### ISSUE TITLE
reduce manual intervention during config/deploy

### ISSUE THREAD

**Issue by ahgraber** [crowdsecurity/helm-charts#81]
Currently, deploying `crowdsec` and `crowdsec-traefik-bouncer` (or, any bouncer) requires manually creating the bouncer API, which means that gitops / infra-as-code is not possible.  It would be really nice to be able to either:

1. specify that the `crowdsec` deployment should pre-create keys and store them as secrets, or 
2. have `crowdsec-traefik-bouncer` create its own key

I realize this is not as simple as it seems on the surface, because of the possible separation between the agent(s) and LAPI(s).

**Comment by he2ss** [comment]
Hi @ahgraber,

You can already register a bouncer with a given key using the env variable `BOUNCER_KEY_<name>=<key>`.
Here is the [docker image documentation](https://hub.docker.com/r/crowdsecurity/crowdsec).

So you set the env variable in the crowdsec helm chart to register the bouncer in the LAPI, then use this key in your bouncer.

**Comment by ahgraber** [comment]
Exactly what I was looking for!  TYVM, and apologies for missing it in the docs.
