### ISSUE TITLE
Add Grafana dashboards to crowdsec helm chart

### ISSUE THREAD

**Issue by Huskydog9988** [crowdsecurity/helm-charts#84]
Adding the dashboards to the helm chart itself would just be one less thing we as a team have to manage. A great example of an implementation of this is in the [falco-exporter chart](https://github.com/falcosecurity/charts/tree/master/falco-exporter).

**Comment by he2ss** [comment]
Hi @Huskydog9988,

Thanks for your patience and for suggesting the dashboard integration. 
We've given it thought but have decided not to proceed with this feature for now. Our primary concern is the diverse setups of our users, many of whom already use their own Grafana instances. Adding this to the helm chart would significantly increase our support scope, especially when our current focus is on improving the core features of CrowdSec.

Thanks for your understanding.
