### ISSUE TITLE
[FEATURE]: Add support for configuring Postgresql and number of replicas for LAPI

### ISSUE THREAD

**Issue by aleksasiriski** [crowdsecurity/helm-charts#94]
Currently with SQLite only one replica is possible for LAPI which sometimes restarts and leads to downtime on all ingresses that use the middleware. This can be easily circumvented by adding Postgresql env config and option to increase replicas for the LAPI deployment, making it HA.

**Comment by he2ss** [comment]
related to https://github.com/crowdsecurity/helm-charts/pull/126 and https://github.com/crowdsecurity/helm-charts/pull/112

**Comment by he2ss** [comment]
Hi @aleksasiriski,

The new release allows you to perform what you need. Here is an example : https://github.com/crowdsecurity/helm-charts/tree/main/charts/crowdsec#setup-for-high-availability
